# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shit Brett Thinks
email: brett@brett.geek.nz
description: > # this means to ignore newlines until "baseurl:"
  Stuff I feel is worth writing, whether for the benefit of others,
  or my future self.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bwilkins.github.io"
twitter_username: bjmaz
github_username:  bwilkins

# Build settings
markdown: kramdown
